Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,7 @@ on:
 env:
   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
   CLUSTER_NAME: traice-private-cluster
-  CLUSTER_ZONE: us-east1-b
+  CLUSTER_REGION: us-east1
 
 jobs:
   deploy:
@@ -28,7 +28,6 @@ jobs:
       run: |
         gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
 
-
     - name: Build and push Docker image
       run: |
         docker build -t us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-node-app-repo/gcp-node-app:$GITHUB_SHA .
@@ -37,7 +36,7 @@ jobs:
     - name: Get GKE credentials
       run: |
         gcloud container clusters get-credentials $CLUSTER_NAME \
-          --zone $CLUSTER_ZONE
+          --region $CLUSTER_REGION
 
     - name: Create namespace if not exists
       run: |
@@ -47,6 +46,12 @@ jobs:
       run: |
         kubectl apply -f k8s/
 
-    - name: Show resources
+    - name: Force update with new image
+      run: |
+        kubectl set image deployment/gcp-node-app \
+          gcp-node-app=us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-node-app-repo/gcp-node-app:$GITHUB_SHA \
+          -n jibin || echo "Deployment not found — skipping rollout"
+
+    - name: Show all resources in 'jibin' namespace
       run: |
         kubectl get all -n jibin
